config/routes.rb
Rails.application.routes.draw do
  resources :settings
  resources :questions
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"

  # Signup routes ("/signup")
  post "signup", to: "users#create"
  get  "signup", to: "users#new"

  # Session routes ("/login")
  post "login", to: "sessions#create"
  get  "login", to: "sessions#new"

  # Logout route ("/logout")
  delete "logout", to: "sessions#destroy"

  # Account routes ("/account")
  put    "account", to: "users#update"
  get    "account", to: "users#edit"
  delete "account", to: "users#destroy"

  # Password routes ("/passwords")
  resources :passwords, only: [:create, :edit, :new, :update], param: :password_reset_token

  # Confirmation routes
  resources :confirmations, only: [:create, :edit, :new], param: :confirmation_token

  # Active seessions
  resources :active_sessions, only: [:destroy] do
    collection do
      delete "destroy_all"
    end
  end

  # Games routes ("/quizzes")
  resources :quizzes

end

app/models/user.rb
class User < ApplicationRecord
  # We do not save the password, but the password diget after generating it using Argon2
  attr_accessor :password
  attr_accessor :current_password

  # Callbacks
  before_save :downcase_email, if: :will_save_change_to_email?
  before_save :generate_password_digest

  # Mailer configuration
  MAILER_FROM_EMAIL = "<Watee Mailer> no-reply@wat.ee"
  CONFIRMATION_TOKEN_EXPIRATION = 1.day
  PASSWORD_RESET_TOKEN_EXPIRATION = 20.minutes

  # Relations
  has_many :quizzes, dependent: :destroy
  has_many :active_sessions, dependent: :destroy
  has_one  :setting, dependent: :destroy

  # Active Storage & Action Text
  has_rich_text    :bio
  has_one_attached :avatar

  # Validations
  validates :email, presence: true, uniqueness: { case_sensitive: false }, format: {with: URI::MailTo::EMAIL_REGEXP}
  validates :password, presence: true, length: { minimum: 6, maximum: 35 }, on: :create
  validates :avatar, content_type: ['image/png', 'image/jpeg', 'image/jpg', 'image/gif'], 
                    size: { between: 1.kilobyte..5.megabytes , message: 'is not given between size' }

  ## Functions

  # Return the user full name (first + last names)
  def full_name
    (self.first_name.capitalize + " " + self.last_name.capitalize).strip
  end

  # Authenticate the user (aka validates the password)
  def authenticate(password)
    require 'argon2'
    Argon2::Password.verify_password(password, self.password_digest)
  end

  # Update the confirmation status for this user
  def confirm!
    update_columns(confirmed_at: Time.current, confirmed: true)
  end

  # Send a confirmation email to the user
  def send_confirmation_email!
    confirmation_token = signed_id(purpose: :email_confirmation, expires_in: CONFIRMATION_TOKEN_EXPIRATION)
    UserMailer.confirmation(self, confirmation_token).deliver_now
  end

  # Send a password reset email to the user
  def send_password_reset_email!
    password_reset_token = signed_id(purpose: :reset_password, expires_in: PASSWORD_RESET_TOKEN_EXPIRATION)
    UserMailer.password_reset(self, password_reset_token).deliver_now
  end

  private
  
  # Make sure we save all emails in lowercase
  def downcase_email
    self.email = email.downcase
  end

  # Hash the password using Argon2
  def generate_password_digest
    require 'argon2'
    if password.present?
      self.password_digest = Argon2::Password.create(password)
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:edit, :destroy, :update]
  before_action :redirect_if_authenticated, only: [:create, :new]

  def create
    @user = User.new(create_user_params)
    if @user.save
      @user.send_confirmation_email!
      redirect_to root_path, notice: "Please check your email for confirmation instructions."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    current_user.destroy
    reset_session
    redirect_to root_path, notice: "Your account has been deleted."
  end

  def edit
    @user = current_user
    @active_sessions = @user.active_sessions.order(created_at: :desc)
  end

  def new
    @user = User.new
  end

  def update
    @user = current_user
    @active_sessions = @user.active_sessions.order(created_at: :desc)
    msg = "Account updated successfully." # default message

    # If the user's account is locked, do nothing but warn them
    if !@user.locked
      # If the user is updating their email, send a confirmation email and adavise them to check their email
      if update_user_params[:email].present?
        msg = "Email & account updated successfully. Please check your mail for confirmation instructions."
      end

      # Make sure that current_password and password are present if the user is updating their password
      if update_user_params[:password].present? && update_user_params[:current_password].present?
        # Validate the current password
        if !@user.authenticate(update_user_params[:current_password])
          flash.now[:alert] = "The current password you entered is incorrect."
          render :edit, status: :unprocessable_entity
          return
        end
      end

      # Save the user's changes
      if @user.update(update_user_params)
        @user.send_confirmation_email! unless !update_user_params[:email].present?
        redirect_to root_path, notice: msg
      else
        render :edit, status: :unprocessable_entity
      end
    else
      flash.now[:alert] = "Your account has been locked. Please contact support."
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def create_user_params
    params.require(:user).permit(:email, :password, :nickname, :remember_me)
  end

  def update_user_params
    params.require(:user).permit(:email, :nickname, :current_password, :password, :first_name, :last_name, :avatar)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form_errors.html.erb
<!-- app/views/users/_form_errors.html.erb -->
<% if object.errors.any? %>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/users/edit.html.erb
<!-- app/views/users/edit.html.erb -->
<div class="pl-8">
  <h1>About you</h1>
  <%= form_with model: @user, url: account_path, method: :put do |form| %>
    <%= render partial: "shared/form_errors", locals: { object: form.object } %>
    <div data-controller="image-uploader">
      <div>
        <%= image_tag @user.avatar.variant(resize_to_limit: [100, 100]),
            width: 100, height: 100, class: "mask mask-circle",
            'data-image-uploader-target': 'preview' if @user.avatar.attached? %>
        <%= content_tag :img, nil, src: "http://tinygraphs.com/spaceinvaders/#{current_user.nickname.strip}?theme=frogideas&numcolors=4&size=100&fmt=svg", width: 100, height: 100,
            class: "mask mask-circle",
            'data-image-uploader-target': 'preview' unless @user.avatar.attached? %>
      </p>
    </div>
    <div class="flex-1 space-x-2 py-4">
      <%= form.label :avatar %>
      <%= form.file_field :avatar, 
          direct_upload: true, 
          accept: "image/gif, image/png, image/jpg, image/jpeg",
          'data-action': 'image-uploader#changed',
          'data-image-uploader-target': 'input' %>
    </div>
    <div data-image-uploader-target="error_message" class="hidden text-sm text-error">
      An error occured while uploading the image.
    </div>
  </div>
  <div class="flex-1 space-x-2 py-4">
    <%= form.label :first_name %>
    <%= form.text_field :first_name, onfocus: "this.setSelectionRange(this.value.length,this.value.length);", class: "input input-bordered w-full max-w-xs" %>
  </div>
  <div class="flex-1 space-x-2 py-4">
    <%= form.label :last_name %>
    <%= form.text_field :last_name, onfocus: "this.setSelectionRange(this.value.length,this.value.length);", class: "input input-bordered w-full max-w-xs" %>
  </div>
  <div class="flex-1 space-x-2 py-4">
    <%= form.label :nickname %>
    <%= form.text_field :nickname, onfocus: "this.setSelectionRange(this.value.length,this.value.length);", class: "input input-bordered w-full max-w-xs" %>
  </div>
  <div class="flex-1 space-x-2 py-4">
    <%= form.label :bio %>
    <%= form.rich_text_area :bio %>
  </div>
  <%= form.submit "Update Account", class: "btn btn-primary" %>
<% end %>
<h1>Account management</h1>
<%= form_with model: @user, url: account_path, method: :put do |form| %>
  <%= render partial: "shared/form_errors", locals: { object: form.object } %>
  <div class="flex-1 space-x-2 py-4">
    <%= form.label :email, "Current Email" %>
    <%= form.email_field :email, class: "input input-bordered w-full max-w-xs" %>
    <p>
      Be careful when changing your email address. You will need to confirm the new one in order to access your account.
    </p>
  </div>
  <h4>PASSWORD CHANGE</h4>
  <div class="flex-1 space-x-2 py-4">
    <%= form.label :current_password %>
    <%= form.password_field :current_password, autocomplete: "current-password", class: "input input-bordered w-full max-w-xs" %>
  </div>
  <div class="flex-1 space-x-2 py-4">
    <%= form.label :password, "New Password" %>
    <%= form.password_field :password, autocomplete: "new-password", class: "input input-bordered w-full max-w-xs" %>
  </div>
  <%= form.submit "Update Account", class: "btn btn-primary" %>
<% end %>
<h1>Active session(s)</h1>
<%= form_with model: @user, url: account_path, method: :put do |form| %>
  <%= render partial: "shared/form_errors", locals: { object: form.object } %>
  <% if @active_sessions.any? %>
    <%= button_to "Log out of all other sessions", destroy_all_active_sessions_path, method: :delete %>
    <table>
      <thead>
        <tr>
          <th>User Agent</th>
          <th>IP Address</th>
          <th>Signed In At</th>
          <th>Sign Out</th>
        </tr>
      </thead>
      <tbody>
        <%= render @active_sessions %>
      </tbody>
    </table>
  <% end %>
<% end %>
<h1>DANGER ZONE</h1>
<div>
  <%= link_to "Delete Account", account_path, data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "btn btn-outline btn-error" %>
</div>
</div>

app/views/users/new.html.erb
<!-- app/views/users/new.html.erb -->
<div class="mx-auto max-w-lg">
  <div class="flex flex-col items-center pt-28">
    <div>
      <h1>
        Sign Up
      </h1>
    </div>
    <div class="flex flex-col mt-4 w-72">
      <%= form_with model: @user, url: signup_path, html: { autocomplete: "on" } do |form| %>
        <%= render partial: "shared/form_errors", locals: { object: form.object } %>
        <div class="space-y-2">
          <div><%= form.label :email, class: "label-text" %></div>
          <%= form.email_field :email, required: true, autofocus: :on, autocomplete: "email", placeholder: "ex. john@example.com", class: "input input-bordered w-full" %>
        </div>
        <div class="space-y-2 py-4">
          <div><%= form.label :nickname, class: "label-text" %></div>
          <%= form.text_field :nickname, required: true, autocomplete: "nickname", placeholder: "ex. RobErTO", class: "input input-bordered w-full" %>
        </div>
        <div class="space-y-2">
          <div><%= form.label :password, class: "label-text" %></div>
          <%= form.password_field :password, required: true, autocomplete: "new-password", class: "input input-bordered w-full" %>
        </div>
        <%= form.submit "Sign Up", class: "btn btn-primary mt-4" %>
      <% end %>
    </div>
    <div class="pt-3">
      <div>
        <%= link_to "Already have an account, Sign in!", login_path, class: "link link-accent" %>
      </div>
    </div>
  </div>
</div>