config/routes.rb
Rails.application.routes.draw do
  resources :settings
  resources :questions
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"

  # Signup routes ("/signup")
  post "signup", to: "users#create"
  get  "signup", to: "users#new"

  # Session routes ("/login")
  post "login", to: "sessions#create"
  get  "login", to: "sessions#new"

  # Logout route ("/logout")
  delete "logout", to: "sessions#destroy"

  # Account routes ("/account")
  put    "account", to: "users#update"
  get    "account", to: "users#edit"
  delete "account", to: "users#destroy"

  # Password routes ("/passwords")
  resources :passwords, only: [:create, :edit, :new, :update], param: :password_reset_token

  # Confirmation routes
  resources :confirmations, only: [:create, :edit, :new], param: :confirmation_token

  # Active seessions
  resources :active_sessions, only: [:destroy] do
    collection do
      delete "destroy_all"
    end
  end

  # Games routes ("/quizzes")
  resources :quizzes

end

app/models/setting.rb
class Setting < ApplicationRecord
  before_create :default_values

  belongs_to :user

  enum theme: {
    "light": 0,
    "dark": 1,
    "cupcake": 2,
    "emerald": 3,
    "corporate": 4,
    "synthwave": 5,
    "valentine": 6,
    "halloween": 7,
    "garden": 8,
    "aqua": 9,
    "pastel": 10,
    "fantasy": 11,
    "wireframe": 12,
    "luxury": 13,
    "business": 14,
    "acid": 15,
    "lemonade": 16,
    "night": 17,
    "coffee": 18,
    "winter": 19,
  }

  private

  def default_values
    self.theme = 0
    self.lang = 'en'
  end

end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  before_action :set_setting, only: %i[ show edit update destroy ]

  # GET /settings or /settings.json
  def index
    @settings = Setting.all
  end

  # GET /settings/1 or /settings/1.json
  def show
  end

  # GET /settings/new
  def new
    @setting = Setting.new
  end

  # GET /settings/1/edit
  def edit
  end

  # POST /settings or /settings.json
  def create
    @setting = Setting.new(setting_params)

    respond_to do |format|
      if @setting.save
        format.html { redirect_to setting_url(@setting), notice: "Setting was successfully created." }
        format.json { render :show, status: :created, location: @setting }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @setting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /settings/1 or /settings/1.json
  def update
    respond_to do |format|
      if @setting.update(setting_params)
        format.html { redirect_to setting_url(@setting), notice: "Setting was successfully updated." }
        format.json { render :show, status: :ok, location: @setting }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @setting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /settings/1 or /settings/1.json
  def destroy
    @setting.destroy

    respond_to do |format|
      format.html { redirect_to settings_url, notice: "Setting was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_setting
      @setting = Setting.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def setting_params
      params.require(:setting).permit(:theme, :lang)
    end
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/views/settings/_form.html.erb
<%= form_with(model: setting) do |form| %>
  <% if setting.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(setting.errors.count, "error") %> prohibited this setting from being saved:</h2>

      <ul>
        <% setting.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :theme, style: "display: block" %>
    <%= form.number_field :theme %>
  </div>

  <div>
    <%= form.label :lang, style: "display: block" %>
    <%= form.text_field :lang %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/settings/_setting.html.erb
<div id="<%= dom_id setting %>">
  <p>
    <strong>Theme:</strong>
    <%= setting.theme %>
  </p>

  <p>
    <strong>Lang:</strong>
    <%= setting.lang %>
  </p>

</div>

app/views/settings/edit.html.erb
<h1>Editing setting</h1>

<%= render "form", setting: @setting %>

<br>

<div>
  <%= link_to "Show this setting", @setting %> |
  <%= link_to "Back to settings", settings_path %>
</div>

app/views/settings/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Settings</h1>

<div id="settings">
  <% @settings.each do |setting| %>
    <%= render setting %>
    <p>
      <%= link_to "Show this setting", setting %>
    </p>
  <% end %>
</div>

<%= link_to "New setting", new_setting_path %>

app/views/settings/new.html.erb
<h1>New setting</h1>

<%= render "form", setting: @setting %>

<br>

<div>
  <%= link_to "Back to settings", settings_path %>
</div>

app/views/settings/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @setting %>

<div>
  <%= link_to "Edit this setting", edit_setting_path(@setting) %> |
  <%= link_to "Back to settings", settings_path %>

  <%= button_to "Destroy this setting", @setting, method: :delete %>
</div>